//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siswa
    {
        public string NIS { get; set; }
        public string Nama { get; set; }
        public System.DateTime TanggalLahir { get; set; }
        public string JenisKelamin { get; set; }
        public string Alamat { get; set; }
    }
}
